In [39]:
#importing numpy as given an alias np, later we will refer np
import numpy as np

In [40]:
myPythonTwoDList = [[1,2,3],[4,5,6]]

In [42]:
type(myPythonTwoDList)

list

In [43]:
myPythonTwoDList

[[1, 2, 3], [4, 5, 6]]

In [44]:
myNumpyArray = np.array(myPythonTwoDList)

In [45]:
myNumpyArray.shape

(2, 3)

In [46]:
type(myNumpyArray)

numpy.ndarray

In [47]:
myNumpyArray

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
#create numpy array with specific data type say integer
myInt16Array = np.array([1, 2, 3], dtype=np.int16)

In [52]:
myInt16Array.dtype

dtype('int16')

In [53]:
#create numpy array with complex datatype
myComplexArray = np.array([ [1,2], [3,4] ], dtype=complex)

In [54]:
myComplexArray.dtype

dtype('complex128')

In [55]:
myComplexArray

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [60]:
#To create sequences of numbers, NumPy provides a function analogous to range of python called arange function
#It create a sequence of number ranging between 10 and 30 with a step of 5
x= np.arange( 10, 30, 5 )

In [63]:
type(x)

numpy.ndarray

In [64]:
x

array([10, 15, 20, 25])

In [70]:
x = np.linspace( 0, 2, 9 )

In [71]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [73]:
newArray = np.array([[1,2,3],[4,5,6]])

In [75]:
xx=newArray.T
xx

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
xx.T

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
from numpy import newaxis
E = np.array([1,2,3])
E
F = np.array([[4,5,6],[7,8,9]])
F

array([[4, 5, 6],
       [7, 8, 9]])

In [80]:
np.row_stack ((E[:,newaxis],F[:,newaxis]))

ValueError: all the input arrays must have same number of dimensions

In [81]:
E[:,newaxis]

array([[1],
       [2],
       [3]])

In [82]:
F[:,newaxis]

array([[[4, 5, 6]],

       [[7, 8, 9]]])

In [83]:
np.column_stack((E[:,newaxis],F[:,newaxis]))

ValueError: all the input arrays must have same number of dimensions